import { Inter } from "next/font/google";
import "./globals.css";
import clsx from "clsx";
import FireFlyesBackground from "@/components/FireFlyesBackground";
import Sound from "@/components/Sound";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata = {
  title: "John's Portfolio",
  description: "Generated by John Lanza",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={clsx(inter.variable, "bg-background text-foreground font-inter overflow-x-hidden")}>
        {children}
        <FireFlyesBackground />
        <Sound />
        <div id="my-modal"/>
      </body>
    </html>
  );
}
