/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Misam Ali Rizvi (https://sketchfab.com/MisamAliRizvi)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/iphone-14-8b65f1a14895490b960f760edece77f0
Title: iPhone 14
*/
"use client";

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export default function Iphone(props) {
  const { nodes, materials } = useGLTF('/models/iphone-transformed.glb')
  const modelRef = useRef();


  useFrame(()=>{
    modelRef.current.rotation.y += 0.005;
  })

  return (
    <group {...props} dispose={null} scale={[20,20,20]} position={[0.05,-1,0]} ref={modelRef} >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Button_04_iPhone_14_0.geometry}
        material={materials.iPhone_14}
        position={[-0.022, 0.085, 0.003]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.011}
      />
    </group>
  )
}

useGLTF.preload('/models/iphone-transformed.glb')
